# Generated by Django 2.0.6 on 2018-12-15 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20181215_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataloggingmodel',
            old_name='air_temp',
            new_name='Air_Temp',
        ),
        migrations.RenameField(
            model_name='dataloggingmodel',
            old_name='humidity',
            new_name='Humidity',
        ),
        migrations.RenameField(
            model_name='dataloggingmodel',
            old_name='soil_moist',
            new_name='Soil_Moisture',
        ),
        migrations.RenameField(
            model_name='dataloggingmodel',
            old_name='soil_temp',
            new_name='Soil_Temp',
        ),
    ]
