# Generated by Django 2.0.6 on 2018-12-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20181215_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataloggingmodel',
            name='Pressure',
            field=models.FloatField(blank=True, default=5984),
            preserve_default=False,
        ),
    ]
